Adições e Correções de Componentes, Ajustes de Configuração e Melhoria no Código
Mined-Development-Company/comunity-projecty pull request #19
Opened 2024-12-22 20:01 UTC by Frotas

## Descrição:

Este PR inclui uma série de alterações e melhorias descritas nos commits abaixo:

1. **[feat(ui/tabs): Adição de componente de navegação por `tabs`](#022af05)**
   - Implementação de um componente reutilizável para navegação com abas.
2. **[feat(ui/card): Adição do componente de `Card` reutilizável](#0169af7)**
   - Criação de um componente `Card` para melhorar a consistência do design.
3. **[build: Ajuste das configurações do NextJS de acordo com a `NODE_ENV`](#b007352)**
   - Ajustes para garantir o comportamento adequado em diferentes ambientes.
4. **[fix(page/auth): Correção de erro na análise do `localStorage`](#930853e)**
   - Tratamento para garantir que a janela seja definida antes de acessar o `localStorage`.
5. **[fix(api/auth): Correção do erro do ESLint: 'handle potential undefined'](#6386532)**
   - Ajustes nos callbacks para tratar valores indefinidos no componente `AuthCard`.
6. **[fix(lint): Correção de importação e problemas de consistência de tipo](#b152211)**
   - Ajuste de importações para cumprir regras do ESLint e remoção de dependências obsoletas.
7. **[fix(ui/modal): Correção de comportamento da propriedade `defaultCloseButton`](#64db5f5)**
   - Alteração do comportamento padrão e correção do estilo aplicado.
8. **[feat(ui/badge): Adição de componente de `badge` personalizado](#0372ec0)**
   - Criação de um badge estilizado para notificações.
9. **[feat(ui/skeleton): Adição de um componente `Skeleton`](#49dc626)**
   - Skeleton loader para interfaces que carregam dados assíncronos.
10. **[fix(ui/header): Correção de redirecionamento de rota]](#af4d03b)**
    - Ajuste em comportamentos de roteamento.
11. **[chore: Adição de condicional para execução do MSW](#f20e5c7)**
    - Ajustes para garantir o comportamento adequado em diferentes ambientes.
13. **[feat(utils/time): Função para formatação de data e timestamps](#eaedce6)**
    - Nova função para formatação amigável de datas e `timestamps`.

## Alterações realizadas:

- **Novos componentes**: `tabs`, `Card`, `badge`, `Skeleton`.
- **Correções gerais**: ESLint, redirecionamentos de rotas, comportamentos padrão em componentes.
- **Configurações**: Ajustes no NextJS e no MSW.
- **Melhorias utilitárias**: Função para formatação de datas.

## Testes:

- Todos os componentes foram testados manualmente e os problemas corrigidos foram verificados. 
- Recomenda-se a execução de testes adicionais para garantir a estabilidade.

2024-12-24 01:36 UTC, 0rogerinho requested changes

2024-12-24 01:36 UTC, 0rogerinho commented on src/shared/@types/index.ts
> +export interface UserProps {
o padrão que estamos utilizando no projeto é type

2024-12-24 01:36 UTC, 0rogerinho commented on src/shared/components/molecules/cardInfo/index.tsx
> +interface CardInfoProps {
estamos usando o padrão de type

2024-12-24 01:36 UTC, 0rogerinho commented on src/shared/components/organisms/header/components/Profile.tsx
> +interface ProfileProps {
estamos usando type como padrão

2024-12-26 14:18 UTC, Frotas commented on src/shared/@types/index.ts
> +export interface UserProps {
Entendi, sendo assim, teria de fazer a alteração das regras do **ESLint** para que ele mantenha e ignore isso.

2024-12-26 23:33 UTC, 0rogerinho commented on src/shared/@types/index.ts
> +export interface UserProps {
eu ja fiz a alteração do eas lint, do dar o pull na develop

2024-12-28 00:29 UTC, 0rogerinho approved these changes

2024-12-28 00:29 UTC, merged